### PR TITLE
Rewrite LED handler.

### PR DESCRIPTION
**Pull request by V10lator**
This allows for setting a duration which will be needed in further PRs.
It also changes NOTIF_LED into a usable enum, changes how elements are defined and adds new ones for purple.

### CODE REVIEW

**Comment by GaryOderNichts** [comment]
Hmm, not quite a fan of creating a new thread every time the LED needs to be updated.

**Comment by V10lator** [comment]
The thread is created when a delay is passed to the function only so it switches back to the old state after said delay.
How to implement such a delay without a new thread?

**Comment by filipe-maia** [comment]
Just adding this issue here, because seems to be related:
https://github.com/GaryOderNichts/recovery_menu/issues/18

**Comment by GaryOderNichts** [comment]
@V10lator Can you test the implementation I made in [feature/led_handler](https://github.com/GaryOderNichts/recovery_menu/tree/feature/led_handler) and refactor your two other PRs on top of it, if it works as expected?

**Comment by GaryOderNichts** [comment]
The other PRs have now been implemented on top of [feature/led_handler](https://github.com/GaryOderNichts/recovery_menu/tree/feature/led_handler).

**Pull request closed without merging**
